config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Public routes
  root to: 'public#index'

  resources :issues, only: [:index] do
    resources :posts, only: %i[index show]
  end

  resources :news, only: %i[index show]
  resources :papers, only: %i[index show]
  resources :subscribers, only: %i[index create new] do
    get :confirm, on: :member
    get :unsubscribe, on: :member
  end
  get 'stores(/:country)' => 'stores#index', as: :stores

  resource :about, only: [:show], controller: 'about'
  resource :search, only: [:show], controller: 'search'
  resource :impressum, only: [:show], controller: 'impressum'
  get '/datenschutz', to: 'dsgvo#show', as: :dsgvo

  # Admin routes
  get 'admin' => 'admin/issues#index', as: :admin

  namespace :admin do
    # Login
    get 'login' => 'login#form'
    post   'login' => 'login#login'
    delete 'login' => 'login#logout'

    # Users
    get    'profile' => 'users#profile'
    put    'profile' => 'users#update_profile'
    patch  'profile' => 'users#update_profile'

    resources :users, except: [:show]

    resources :issues, except: [:show] do
      resources :posts
    end

    resources :posts, only: [] do
      resource :gallery, only: %i[create destroy]
    end

    resources :papers
    resources :news
    resources :authors

    resources :newsletters do
      post :sendletter, on: :member
    end

    resources :subscribers, only: %i[index destroy]

    resources :attachment_sets, only: [] do
      resources :attachments, only: %i[create destroy]
    end

    # Settings
    resource  :about, only: %i[edit show update], controller: 'about'
    resource  :dsgvo, only: %i[edit show update], controller: 'dsgvo'
    resource  :impressum, only: %i[edit show update], controller: 'impressum'
    resources :links, except: [:show]
    resource :newsletter_info, only: %i[edit update], controller: 'newsletter_info'
    resource :sales_info, only: %i[edit update], controller: 'sales_info'
    resources :stores, except: [:show]
  end

  # Ajax routes
  namespace :ajax do
    post 'posts/sort' => 'posts#sort'

    resources :attachment_sets, only: [] do
      resources :attachments, only: %i[index create update destroy]
      post 'attachments/sort' => 'attachments#sort'
    end

    resources :uploads, only: %i[index create destroy]
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < PublicController
  # GET /search
  def show
    @title = t('labels.search.public')
    @papers = []
    @issues = []

    return if params[:commit].blank?

    if params[:category].blank?
      @papers = Paper.published.search(params)
      @issues = Issue.reverse_published.search_posts(params)
    elsif params[:category] == 'posts'
      @issues = Issue.reverse_published.search_posts(params)
    elsif params[:category] == 'papers'
      @papers = Paper.published.search(params)
    end

    flash.now[:notice] = t('messages.error.find') if @papers.blank? && @issues.blank?
  end
end

app/views/search/show.html.slim
#filter-mask
  = form_tag search_path, method: :get do
    .filter.category
      = label_tag t('activerecord.attributes.search.category')
      = select_tag :category,
         options_for_select([[t('labels.issue.menu'), 'posts'],[t('labels.paper.menu'), 'papers']], params[:category]),
              include_blank: true
    .filter.issue
      = label_tag t('activerecord.attributes.search.issue')
      = select_tag :issue_id, options_from_collection_for_select(Issue.reverse_published, :id, :title, params[:issue_id]),
              include_blank: true
    .filter
      = label_tag t('activerecord.attributes.search.author')
      = text_field_tag :author, params[:author]
    .filter
      = label_tag t('activerecord.attributes.search.title')
      = text_field_tag :title, params[:title]
    .filter
      = label_tag t('activerecord.attributes.search.query')
      = text_field_tag :body, params[:body]
    = submit_tag t('labels.search.submit')
#content
  - flash.each do |key, val|
    div class=("flash #{key}")
      = val
  - if @papers.any?
    .results
      h3
        = t('labels.paper.menu')
      .titles
        - @papers.each do |paper|
          a.paper-title href="#{paper_path(paper)}"
            = paper.title
            span.date= l paper.updated_at, format: :search
  - @issues.each do |issue|
    .results
      p.date= l issue.created_at, format: :search
      h3
        = issue.title
      .titles
        - issue.posts.each do |post|
          a.post-titles href="#{issue_post_path(issue, post)}"
            span.authors= post.authors.join(", ")
            = post.title