config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Public routes
  root to: 'public#index'

  resources :issues, only: [:index] do
    resources :posts, only: %i[index show]
  end

  resources :news, only: %i[index show]
  resources :papers, only: %i[index show]
  resources :subscribers, only: %i[index create new] do
    get :confirm, on: :member
    get :unsubscribe, on: :member
  end
  get 'stores(/:country)' => 'stores#index', as: :stores

  resource :about, only: [:show], controller: 'about'
  resource :search, only: [:show], controller: 'search'
  resource :impressum, only: [:show], controller: 'impressum'
  get '/datenschutz', to: 'dsgvo#show', as: :dsgvo

  # Admin routes
  get 'admin' => 'admin/issues#index', as: :admin

  namespace :admin do
    # Login
    get 'login' => 'login#form'
    post   'login' => 'login#login'
    delete 'login' => 'login#logout'

    # Users
    get    'profile' => 'users#profile'
    put    'profile' => 'users#update_profile'
    patch  'profile' => 'users#update_profile'

    resources :users, except: [:show]

    resources :issues, except: [:show] do
      resources :posts
    end

    resources :posts, only: [] do
      resource :gallery, only: %i[create destroy]
    end

    resources :papers
    resources :news
    resources :authors

    resources :newsletters do
      post :sendletter, on: :member
    end

    resources :subscribers, only: %i[index destroy]

    resources :attachment_sets, only: [] do
      resources :attachments, only: %i[create destroy]
    end

    # Settings
    resource  :about, only: %i[edit show update], controller: 'about'
    resource  :dsgvo, only: %i[edit show update], controller: 'dsgvo'
    resource  :impressum, only: %i[edit show update], controller: 'impressum'
    resources :links, except: [:show]
    resource :newsletter_info, only: %i[edit update], controller: 'newsletter_info'
    resource :sales_info, only: %i[edit update], controller: 'sales_info'
    resources :stores, except: [:show]
  end

  # Ajax routes
  namespace :ajax do
    post 'posts/sort' => 'posts#sort'

    resources :attachment_sets, only: [] do
      resources :attachments, only: %i[index create update destroy]
      post 'attachments/sort' => 'attachments#sort'
    end

    resources :uploads, only: %i[index create destroy]
  end
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  belongs_to :city
  delegate :country, to: :city, allow_nil: true
  delegate :country_id, to: :city, allow_nil: true

  validates :name, presence: true
  validates :url, format: URI::DEFAULT_PARSER.make_regexp(%w[http https]), allow_blank: true

  default_scope { order(:city_id) }

  after_initialize :init_city
  after_destroy :cleanup

  def self.search(params)
    result = self

    result = result.where('name LIKE ?', "%#{params[:name]}%") if params[:name].present?

    result = result.joins(:city).where('city LIKE ?', "%#{params[:city]}%") if params[:city].present?

    result = result.joins(:city).where('cities.country_id = ?', params[:country_id]) if params[:country_id].present?

    result
  end

  def city_attributes=(city)
    self.city = City.find_or_init_city(city)
  end

  private

  def init_city
    self.city = City.new if city.nil?
  end

  # Destroy city if not longer needed
  def cleanup
    city.destroy if city.stores.count.zero?
  end
end

app/controllers/admin/stores_controller.rb
# frozen_string_literal: true

module Admin
  class StoresController < Admin::ApplicationController
    before_action :find_countries, only: %i[new create edit update]
    before_action :find_store,     only: %i[edit update destroy]

    # DET /admin/stores
    def index
      @sales_info = SalesInfo.new
      @stores = Store.search(params).page(params[:page]).limit(15)
      @countries = Country.with_stores.uniq
      @title = t('labels.store.index')
    end

    # GET /admin/stores/new
    def new
      @store = Store.new
      @title = t('labels.store.menu')
      @subtitle = t('labels.store.new')
      render :form
    end

    # POST /admin/stores
    def create
      @store = Store.new(store_params)

      if @store.save
        flash[:notice] = t('messages.store.success.save', name: @store.name)
        redirect_to admin_stores_url
      else
        flash.now[:alert] = t('messages.store.error.save')
        @title = t('labels.store.menu')
        @subtitle = t('labels.store.new')
        render :form
      end
    end

    # GET /admin/stores/:id/edit
    def edit
      @country = @store.country
      @title = t('labels.store.menu')
      @subtitle = @store.name
      render :form
    end

    # PUT /admin/stores/:id
    def update
      if @store.update(store_params)
        flash[:notice] = t('messages.success.save')
        redirect_to admin_stores_url
      else
        flash.now[:alert] = t('messages.error.save')
        @title = t('labels.store.menu')
        @subtitle = @store.name
        render :form
      end
    end

    # DELETE /admin/stores/:id
    def destroy
      if @store.destroy
        flash[:notice] = t('messages.store.success.delete', name: @store.name)
      else
        flash[:alert] = t('messages.error.delete')
      end

      redirect_to admin_stores_url
    end

    private

    def store_params
      params.require(:store)
            .permit(:name, :direction, :url,
                    city_attributes: %i[id city country_id])
    end

    def find_countries
      @countries = Country.all
    end

    def find_store
      @store = Store.find(params[:id])
    end
  end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < PublicController
  # GET /stores(/:country)
  def index
    @countries = Country.with_stores.ordered
    @sales_info_body = SalesInfo.new.body

    @country = if params[:country].present?
                 @countries.find { |c| c.country == params[:country] }
               else
                 @countries.first
               end

    # Raise 404 when country code in url not found
    if @countries.length.positive? && @country.nil?
      raise ActionController::RoutingError, t('messages.country.error.not_found')
    end

    @title = t('labels.store.public')
  end
end

app/views/admin/stores/form.html.slim
= form_for [:admin, @store] do |f|
  - unless @store.errors.empty?
    = render 'admin/shared/validation_errors', model: @store
  div
    = f.label :name
    = f.text_field :name
  div
    = f.label :direction
    = f.text_field :direction
  = f.fields_for :city, @store.city do |c|
    .city
      = c.label :city
      = c.text_field :city
    .country
      = c.label :country
      = text_field_tag nil, @country.try(:human), id: 'list-countries', data: {countries: @countries}
      = c.hidden_field :country_id
  div
    = f.label :url
    = f.text_field :url, placeholder: 'http://'
  = f.submit t('actions.save')

app/views/admin/stores/index.html.slim
.add-entry
  = link_to new_admin_store_path do
    i.fas.fa-plus-circle
    = t('labels.store.new')
.index-filter
  = form_tag admin_stores_path, method: :get do
    = text_field_tag :name, params[:name], placeholder: Store.human_attribute_name(:name)
    = country_select_tag @countries, :country_id, params[:country_id], prompt: (Store.human_attribute_name :country)
    = text_field_tag :city, params[:city], placeholder: Store.human_attribute_name(:city)
    = link_to t('actions.clear'), admin_stores_path, class: "clear"
    = submit_tag t('actions.filter')

#info
  .show.info-content
    h3= @sales_info.title
    = markdown(@sales_info.body)
  .edit-info
    = link_to edit_admin_sales_info_path do
      i.fas.fa-pencil-alt
      = t('actions.edit')

- if @stores.any?
  = will_paginate
  table.index-table
    thead
      tr
        - [:name, :direction, :url].each do |attr|
          th
            = Store.human_attribute_name(attr)
        th
    - @stores.each do |store|
      tr
        td
          = store.name
        td
          p
            = store.direction
          p
            = store.city.city
        td.stores-url
          = link_to store.url, store.url
        td.actions
          = link_to edit_admin_store_path(store) do
            i.fas.fa-pencil-alt
            = t('actions.edit')
          = button_to admin_store_path(store), method: :delete, data: { confirm: "Wirklich löschen?" } do
            i.fas.fa-trash
- else
  .no-results
    = t('messages.error.find')