config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Public routes
  root to: 'public#index'

  resources :issues, only: [:index] do
    resources :posts, only: %i[index show]
  end

  resources :news, only: %i[index show]
  resources :papers, only: %i[index show]
  resources :subscribers, only: %i[index create new] do
    get :confirm, on: :member
    get :unsubscribe, on: :member
  end
  get 'stores(/:country)' => 'stores#index', as: :stores

  resource :about, only: [:show], controller: 'about'
  resource :search, only: [:show], controller: 'search'
  resource :impressum, only: [:show], controller: 'impressum'
  get '/datenschutz', to: 'dsgvo#show', as: :dsgvo

  # Admin routes
  get 'admin' => 'admin/issues#index', as: :admin

  namespace :admin do
    # Login
    get 'login' => 'login#form'
    post   'login' => 'login#login'
    delete 'login' => 'login#logout'

    # Users
    get    'profile' => 'users#profile'
    put    'profile' => 'users#update_profile'
    patch  'profile' => 'users#update_profile'

    resources :users, except: [:show]

    resources :issues, except: [:show] do
      resources :posts
    end

    resources :posts, only: [] do
      resource :gallery, only: %i[create destroy]
    end

    resources :papers
    resources :news
    resources :authors

    resources :newsletters do
      post :sendletter, on: :member
    end

    resources :subscribers, only: %i[index destroy]

    resources :attachment_sets, only: [] do
      resources :attachments, only: %i[create destroy]
    end

    # Settings
    resource  :about, only: %i[edit show update], controller: 'about'
    resource  :dsgvo, only: %i[edit show update], controller: 'dsgvo'
    resource  :impressum, only: %i[edit show update], controller: 'impressum'
    resources :links, except: [:show]
    resource :newsletter_info, only: %i[edit update], controller: 'newsletter_info'
    resource :sales_info, only: %i[edit update], controller: 'sales_info'
    resources :stores, except: [:show]
  end

  # Ajax routes
  namespace :ajax do
    post 'posts/sort' => 'posts#sort'

    resources :attachment_sets, only: [] do
      resources :attachments, only: %i[index create update destroy]
      post 'attachments/sort' => 'attachments#sort'
    end

    resources :uploads, only: %i[index create destroy]
  end
end

app/models/newsletter.rb
# frozen_string_literal: true

class Newsletter < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true

  default_scope { order(updated_at: :desc) }

  def self.published
    where(published: true)
  end

  def self.unpublished
    where(published: false)
  end

  def send_to(subscribers)
    subscribers.each do |s|
      NewsletterMailer.delay.send_newsletter(s, self)
    end

    update(published: true)
  end
end

app/controllers/admin/newsletters_controller.rb
# frozen_string_literal: true

module Admin
  class NewslettersController < Admin::ApplicationController
    skip_before_action :authorize
    before_action :find_newsletter, only: %i[show edit update sendletter destroy]

    # GET /admin/newsletters
    def index
      @unpublished = Newsletter.unpublished
      @published = Newsletter.published.page(params[:page]).limit(15)
      @title = t('labels.newsletter.index')
    end

    # GET /admin/newsletters/:id
    def show
      @title = t('labels.newsletter.menu')
    end

    # GET /admin/newsletters/new
    def new
      @newsletter = Newsletter.new
      @title = t('labels.newsletter.menu')
      @subtitle = t('labels.newsletter.new')
      render :form
    end

    # POST /admin/newsletters
    def create
      @newsletter = Newsletter.new(newsletter_params)
      @newsletter.user = current_user

      if @newsletter.save
        flash[:notice] = t('messages.newsletter.success.save', title: @newsletter.title)
        redirect_to admin_newsletter_url(@newsletter)
      else
        flash.now[:alert] = t('messages.newsletter.error.save')
        @title = t('labels.newsletter.menu')
        @subtitle = t('labels.newsletter.new')
        render :form
      end
    end

    # GET /admin/newsletters/:id/edit
    def edit
      @title = t('labels.newsletter.menu')
      @subtitle = @newsletter.title
      render :form
    end

    # PUT /admin/newsletters/:id
    def update
      @newsletter.user = current_user

      if @newsletter.update(newsletter_params)
        flash[:notice] = t('messages.success.save')
        redirect_to admin_newsletter_url(@newsletter)
      else
        flash.now[:alert] = t('messages.error.save')
        @title = t('labels.newsletter.menu')
        @subtitle = @newsletter.title
        render :form
      end
    end

    # POST /admin/newsletters/:id/sendletter
    def sendletter
      if @newsletter.send_to(Subscriber.confirmed)
        flash[:notice] = t('messages.newsletter.success.published', title: @newsletter.title)
      else
        flash[:alert] = t('messages.newsletter.error.published')
      end

      redirect_to admin_newsletters_url
    end

    # DELETE /admin/newsletters/:id
    def destroy
      if @newsletter.destroy
        flash[:notice] = t('messages.newsletter.success.delete', title: @newsletter.title)
      else
        flash[:alert] = t('messages.error.delete')
      end

      redirect_to admin_newsletters_url
    end

    private

    def newsletter_params
      params.require(:newsletter).permit(:title, :body, :published)
    end

    def find_newsletter
      @newsletter = Newsletter.find(params[:id])
    end
  end
end

app/views/admin/newsletters/form.html.slim
= form_for [:admin, @newsletter] do |f|
  - unless @newsletter.errors.empty?
    = render 'admin/shared/validation_errors', model: @newsletter
  div
    = f.label :title
    = f.text_field :title
  div
    = f.text_area :body, class: 'body'
  = f.submit t('actions.save')

app/views/admin/newsletters/index.html.slim
.add-entry
  = link_to new_admin_newsletter_path do
    i.fas.fa-plus-circle
    = t('labels.newsletter.new')
  - unless Newsletter.any?
  .no-results
    = t('messages.error.find')
- if @unpublished.any?
  table.index-table
    thead
      tr
        th
          = t('labels.newsletter.unpublished')
        th
          = Newsletter.human_attribute_name :update
        th
    - @unpublished.each do |newsletter|
      tr
        td
          = link_to newsletter.title, admin_newsletter_path(newsletter)
        td.update
          = l newsletter.updated_at, format: :long
          .updated_by
            = newsletter.user.username
        td.actions
          = link_to ('actions.edit'), edit_admin_newsletter_path(newsletter), class: 'fas fa-pencil-alt', title: t('actions.edit')
          = button_to admin_newsletter_path(newsletter), method: :delete, data: {confirm: "Wirklich löschen?"} do
            i.fas.fa-trash
= will_paginate @published
- if @published.any?
  table.index-table
    thead
      tr
        th
          = t('labels.newsletter.published')
        th
          = t('labels.newsletter.send')
        th
    - @published.each do |newsletter|
      tr
        td
          = link_to newsletter.title, admin_newsletter_path(newsletter)
        td.update
          = l newsletter.updated_at, format: :long
          .updated_by
            = newsletter.user.username
        td.actions
          = link_to ('actions.show'), admin_newsletter_path(newsletter), class: 'fas fa-truck'
= will_paginate @published

app/views/admin/newsletters/show.html.slim
.show-actions
  - unless @newsletter.published
    = button_to sendletter_admin_newsletter_path(@newsletter) do
      i.fas.fa-envelope
      =  t('actions.send')
    = link_to edit_admin_newsletter_path(@newsletter) do
      i.fas.fa-pencil-alt
      = t('actions.edit')
  = link_to admin_newsletters_path do
    i.fas.fa-check-circle
    = t('actions.back')
.show
  h1
    = @newsletter.title
  = markdown(@newsletter.body)
.show-actions
  - unless @newsletter.published
    = button_to sendletter_admin_newsletter_path(@newsletter) do
      i.fas.fa-envelope
      =  t('actions.send')
    = link_to edit_admin_newsletter_path(@newsletter) do
      i.fas.fa-pencil-alt
      = t('actions.edit')
  = link_to admin_newsletters_path do
    i.fas.fa-check-circle
    = t('actions.back')